name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log Into GitHub
        run:
          echo "${{ secrets.ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main  # Update each submodule to its latest commit
          git add .
          git commit -m "Update submodules"
          git push origin main
