name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log Into GitHub
        run: |
          git config user.email "${{ secrets.EMAIL }}"
          git config user.name "ZS1ROBOTY3D"

      - name: Check for changes
        id: check_changes
        run: |
          changes=$(git status --porcelain)
          if [[ -n "$changes" ]]; then
            echo "Changes found."
            echo "{found_changes}={true}" >> $GITHUB_OUTPUT
          else
            echo "No changes found."
            echo "{found_changes}={false}" >> $GITHUB_OUTPUT
          fi

      - name: Initialize and update submodules
        run: |
          # Skip this part if Check for changes didn't find any changes
          if [[ "${{ steps.check_changes.outputs.should_run }}" == 'true' ]]; then
            git submodule update --init --recursive
            git submodule foreach git pull origin main
            git add .
            git commit -m "Update submodules"
            git push origin main
          else
            echo "Skipping submodule update as no changes were found."
          fi
