name: Update Submodules

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into GitHub
        run: |
          gh auth login --with-token ${{ secrets.auth_token }}

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main  # Update each submodule to its latest commit
          git add .
          git commit -m "Update submodules"
          git push origin main
